make_image:
  stage: build
  script:
    - apt-get update && apt-get -y install wget git
    - wget -O sixs ftp://$AGSFTPCREDS@agsftp.ags.io/gipsftp/sixs
    - wget -O gitlab_ci ftp://$AGSFTPCREDS@agsftp.ags.io/gipsftp/gitlab_ci
    - wget -O gips_creds.sh.enc ftp://$AGSFTPCREDS@agsftp.ags.io/gipsftp/gips_creds.sh.enc
    - git checkout $CI_COMMIT_REF_NAME
    - docker build -t gippy-0.x -f docker/gippy-install.docker docker
    - docker build -t gips_test_$CI_COMMIT_REF_SLUG -f docker/gips-ci.docker .
    - docker system prune -f
  tags:
    - gipsdev

run_tests:
  stage: test
  script:
    - docker run --rm -e GIPS_OVERRIDE_VERSION=0.8.2 gips_test_$CI_COMMIT_REF_SLUG pytest -vv --setup-repo --slow --sys -s -k 'aod'
    - docker image rm gips_test_$CI_COMMIT_REF_SLUG
    - docker system prune -f
  tags:
    - gipsdev

