make_image:
  stage: build
  script:
    - apt-get update && apt-get install wget 
    - wget -O sixs ftp://$AGSFTPCREDS@agsftp.ags.io/gipsftp/sixs
    - wget -O gitlab_ci ftp://$AGSFTPCREDS@agsftp.ags.io/gipsftp/gitlab_ci
    - wget -O gips_creds.sh.enc ftp://$AGSFTPCREDS@agsftp.ags.io/gipsftp/gips_creds.sh.enc
    - git checkout $CI_COMMIT_REF_NAME
    - git merge dev
    - docker build -t gippy-0.x -f docker/gippy-install.docker docker
    - docker build -t gips_test -f docker/gips-ci.docker .
  tags:
    - gipsdev

run_tests:
  stage: test
  script:
    - docker run --rm gips_test pytest -vv --setup-repo --slow --sys -k 'modis or landsat or aod or sentinel2'
  tags:
    - gipsdev

