make_image:
  stage: build
  script:
    - apt-get update && apt-get -y install wget git
    - wget -O sixs ftp://$AGSFTPUSERNAME:$AGSFTPPASSWORD@agsftp.ags.io/gipsftp/sixs
    # TODO need ortho for coreg; needed for CI pipeline?  if so, which one?
    - wget -O ortho ftp://$AGSFTPUSERNAME:$AGSFTPPASSWORD@agsftp.ags.io/gipsftp/ortho
    - cp /home/icooke/bin/ortho ./
    # TODO what is this?
    - wget -O gitlab_ci ftp://$AGSFTPUSERNAME:$AGSFTPPASSWORD@agsftp.ags.io/gipsftp/gitlab_ci
    # TODO what is this?
    - wget -O gips_creds.sh.enc ftp://$AGSFTPUSERNAME:$AGSFTPPASSWORD@agsftp.ags.io/gipsftp/gips_creds.sh.enc
    #- git checkout $CI_COMMIT_SHA # this appears to be pointless
    # old version:
    #- docker build -t gippy-ci -f docker/gippy-install.docker docker
    #- docker build --no-cache
    #  --build-arg GIPS_UID=$(id -u)
    #  -t gips_test_$CI_COMMIT_REF_SLUG
    #  -f docker/gips-ci.docker .
    # trial version
    # TODO needs to be uncommented later:
    #- docker build -t gips-base -f Dockerfile .
    - whoami && pwd && ls -lh
    - docker build -t gips_test_$CI_COMMIT_REF_SLUG -f docker/gips-ci.docker .
  tags:
    - gipsdev
  after_script:
   - docker system prune -f


run_tests:
  stage: test
  script:
    #- whoami && pwd && ls -lh
    - docker run --rm gips-base /bin/echo "everything is under control"
    - docker run --rm gips_test_$CI_COMMIT_REF_SLUG /bin/echo "yeah all good in the hood"
    #- docker run --rm gips_test_$CI_COMMIT_REF_SLUG pytest -vv -s -k unit # TODO both int & unit
    #- docker run --dns=10.0.4.1 --rm
    #  -v /net/cluster/projects/gips-dev/sys-test-assets/:/artifact-store
    #  gips_test_$CI_COMMIT_REF_SLUG
    #  pytest -r es -vv --slow --setup-repo --sys -s -m lite
  tags:
    - gipsdev
  after_script:
    - docker image rm gips_test_$CI_COMMIT_REF_SLUG
    - docker system prune -f


#publish_image:
#  stage: deploy
#  only:
#    - tags
#  script:
#    - apt-get update && apt-get -y install wget git
#    - wget -O sixs ftp://$AGSFTPUSERNAME:$AGSFTPPASSWORD@agsftp.ags.io/gipsftp/sixs
#    - wget -O ortho ftp://$AGSFTPUSERNAME:$AGSFTPPASSWORD@agsftp.ags.io/gipsftp/ortho
#    - git checkout $CI_COMMIT_SHA
#    - VERSION=$(PYTHONPATH=. python -c 'import gips ; print(gips.__version__)')
#    - test -z "$(docker image ls --quiet registry.ags.io/gips:$VERSION)" -a "v$VERSION" = "$CI_COMMIT_REF_NAME"
#    - docker build -t gippy-03x-release -f docker/gippy-release.docker docker
#    # TODO GIPS_VERSION isn't actually used?
#    - docker build --no-cache
#      --build-arg GIPS_VERSION=$VERSION
#      -t registry.ags.io/gips:$VERSION
#      -f docker/gips-production.docker .
#    - docker push registry.ags.io/gips:$VERSION
#    - docker rmi registry.ags.io/gips:$VERSION
#  tags:
#    - gipsdev
#  after_script:
#   - docker system prune -f
